In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("dirty_cafe_sales.csv")
data = pd.DataFrame(data)
data.head()

Transaction ID    Item Quantity Price Per Unit Total Spent  Payment Method  \
0    TXN_1961373  Coffee        2            2.0         4.0     Credit Card   
1    TXN_4977031    Cake        4            3.0        12.0            Cash   
2    TXN_4271903  Cookie        4            1.0       ERROR     Credit Card   
3    TXN_7034554   Salad        2            5.0        10.0         UNKNOWN   
4    TXN_3160411  Coffee        2            2.0         4.0  Digital Wallet   

   Location Transaction Date  
0  Takeaway       2023-09-08  
1  In-store       2023-05-16  
2  In-store       2023-07-19  
3   UNKNOWN       2023-04-27  
4  In-store       2023-06-11

In [12]:
data.describe()

Transaction ID   Item Quantity Price Per Unit Total Spent  \
count           10000   9667     9862           9821        9827   
unique          10000     10        7              8          19   
top       TXN_9226047  Juice        5            3.0         6.0   
freq                1   1171     2013           2429         979   

        Payment Method  Location Transaction Date  
count             7421      6735             9841  
unique               5         4              367  
top     Digital Wallet  Takeaway          UNKNOWN  
freq              2291      3022              159

In [16]:
data['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [73]:
data.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

Abaixo, foram atribuídos os preços corretos em cada tipo de item:

In [44]:
price_coffee = data.loc[data['Item'] == 'Coffee', 'Price Per Unit']
price_coffee.unique()

array([2], dtype=object)

In [43]:
price_coffee[:] = 2
price_coffee.unique()

array([2], dtype=object)

In [25]:
price_cake = data.loc[data['Item'] == 'Cake', 'Price Per Unit']
price_cake.unique()

array(['3.0', nan, 'UNKNOWN', 'ERROR'], dtype=object)

In [26]:
price_cake[:] = 3
price_cake.unique()

array([3], dtype=object)

In [27]:
price_cookie = data.loc[data['Item'] == 'Cookie', 'Price Per Unit']
price_cookie.unique()

array(['1.0', 'UNKNOWN', nan, 'ERROR'], dtype=object)

In [29]:
price_cookie[:] = 1
price_cookie.unique()

array([1], dtype=object)

In [31]:
price_salad = data.loc[data['Item'] == 'Salad', 'Price Per Unit']
price_salad.unique()

array(['5.0', 'ERROR', 'UNKNOWN', nan], dtype=object)

In [33]:
price_salad[:] = 5
price_salad.unique()

array([5], dtype=object)

In [34]:
price_smoothie = data.loc[data['Item'] == 'Smoothie', 'Price Per Unit']
price_smoothie.unique()

array(['4.0', nan, 'UNKNOWN', 'ERROR'], dtype=object)

In [35]:
price_smoothie[:] = 4
price_smoothie.unique()

array([4], dtype=object)

In [36]:
price_sandwich = data.loc[data['Item'] == 'Sandwich', 'Price Per Unit']
price_sandwich.unique()

array(['4.0', nan, 'ERROR', 'UNKNOWN'], dtype=object)

In [37]:
price_sandwich[:] = 4
price_sandwich.unique()

array([4], dtype=object)

In [38]:
price_juice = data.loc[data['Item'] == 'Juice', 'Price Per Unit']
price_juice.unique()

array(['3.0', nan, 'UNKNOWN', 'ERROR'], dtype=object)

In [39]:
price_juice[:] = 3
price_juice.unique()

array([3], dtype=object)

In [40]:
price_tea = data.loc[data['Item'] == 'Tea', 'Price Per Unit']
price_tea.unique()

array(['1.5', nan, 'ERROR', 'UNKNOWN'], dtype=object)

In [41]:
price_tea[:] = 1.5
price_tea.unique()

array([1.5], dtype=object)

Em seguida, optou-se por calcular a quantidade através da divisão de "Total Spent" por "Price Per Unit"

In [8]:
# Valores unicos em Quantity
data['Quantity'].unique()

array(['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan], dtype=object)

In [9]:
# Convertendo para coluna numerica
quant = pd.to_numeric(data['Quantity'], errors='coerce')
price = pd.to_numeric(data['Price Per Unit'], errors='coerce')
total = pd.to_numeric(data['Total Spent'], errors='coerce')

# Verificando se as colunas são numéricas
quant.dtype, price.dtype, total.dtype

(dtype('float64'), dtype('float64'), dtype('float64'))

In [10]:
quant.unique()

array([ 2.,  4.,  5.,  3.,  1., nan])

In [11]:
df = pd.DataFrame(
    {'quant': quant,
     'price': price,
     'total': total}
)
df.head()

quant  price  total
0    2.0    2.0    4.0
1    4.0    3.0   12.0
2    4.0    1.0    NaN
3    2.0    5.0   10.0
4    2.0    2.0    4.0

In [12]:
quant_nan = df[df['quant'].isna()]
quant_nan['quant'].unique()

array([nan])

In [13]:
quant_nan['quant'] = quant_nan['total'] / quant_nan['price']
quant_nan.head()

/tmp/ipykernel_2032/545011256.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quant_nan['quant'] = quant_nan['total'] / quant_nan['price']


quant  price  total
20     5.0    4.0   20.0
55     2.0    1.0    2.0
57     1.0    3.0    3.0
66     2.0    3.0    6.0
117    3.0    3.0    9.0

In [14]:
quant_nan['quant'].unique()

array([ 5.,  2.,  1.,  3.,  4., nan])

In [22]:
quant_nan[quant_nan['quant'].isna()].head()

quant  price  total
236    NaN    5.0    NaN
278    NaN    3.0    NaN
629    NaN    NaN   12.0
641    NaN    3.0    NaN
738    NaN    4.0    NaN